### ISSUE TITLE
Documentation to scripts and angular files

### ISSUE THREAD

**Issue by hmc-cs-sfriedrich** [simsays/Shakespeare#66]
As a developer, I want documentation --including in line comments and a short description of functionality at top of file (if relevant) or in README--so that the code is maintainable.

**Comment by hmc-cs-sfriedrich** [comment]
I took care of the html, css, and Angular files to my liking of detail. Check out the readme.

TODO: Script (Simon)

**Comment by robertmlinden** [comment]
I took care of the html, css, and Angular files to my liking of detail. Check out the readme.

TODO: Script (Simon)

**Comment by hmc-cs-sfriedrich** [comment]
Client wants comments to be about the WHAT rather than the HOW.
